### ISSUE TITLE
Ask for working together with a new project

### ISSUE THREAD

**Issue by densechen** [thiswinex/STBP-simple#1]
你好！
请问您有兴趣一起开发"https://github.com/densechen/eve-mli"这个项目吗？
详细内容：https://github.com/densechen/eve-mli/blob/main/README_cn.md
期待您的回复呀！

**Comment by thiswinex** [comment]
非常抱歉由于疏忽没有及时看到这条issue...

感谢您的认可！您的项目非常优秀，但由于个人精力所限，我可能目前无法分心承担太多该项目的内容。不过本项目预计还会继续增加一部分功能（可能包括使用优化、cuda、LSTM转换以及RL的支持，也可能会以新开一个project的形式），如果您也有这方面的需求，欢迎一起讨论或者合作~

顺祝新春愉快~

**Comment by densechen** [comment]
哈哈哈，新年快乐哈！
关于CUDA等extension，目前也是大家一致追求的目标。
但是，关于SNN的进一步方向，我还保持一个观望的态度。
我给你发了一封邮件（zbhhan@gmail.com），详聊哈！
