### ISSUE TITLE
nmnist model 运行问题

### ISSUE THREAD

**Issue by iridescentMay** [thiswinex/STBP-simple#10]
![image](https://user-images.githubusercontent.com/94227715/149344859-131b39e2-9d9a-4e69-95a1-5e5a19f6eff5.png)
![image](https://user-images.githubusercontent.com/94227715/149345867-dfb2339a-0c60-4dce-9776-bd9532dd11e0.png)

你好，感谢你的复现，我再运行您的代码是遇到如下模型参数问题:
code：        x = x.view(x.shape[0], -1, x.shape[4])
                  print("after reshape",x.shape)
                  x = self.fc1_s(x)

bug： RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x2450 and 313600x500)

 x = self.fc1_s(x)全连接层无法通过，报错矩阵不匹配，不知道是模型参数问题还是我加载数据集的问题，想请教一下您是在跑这部分模型的时候有没有遇到过同样的问题。

**Comment by thiswinex** [comment]
shape不匹配的问题，建议每处打印shape逐步调试。fc层之前的tensor流形状应该是(N,C,H,W,T)，进fc层时的tensor流形状是(N,C*H*W,T)
