### ISSUE TITLE
用resnet-19基础结构训练cifar10

### ISSUE THREAD

**Issue by crashkk** [thiswinex/STBP-simple#11]
作者你好，感谢你的复现。想问一下你用resnet-19作为基础结构时，训练cifar10最高精确度能到多少呢？单卡运行一般需要多久（使用tdBN方法）

**Comment by thiswinex** [comment]
85%左右吧，我没有仔细调超参，再继续训应该还可以提。单卡运行时间不短，具体多久我忘记了
