### ISSUE TITLE
放电频率的统计

### ISSUE THREAD

**Issue by chenjiefighting** [thiswinex/STBP-simple#12]
你好，我是脉冲神经网络的小白，我想问一下放电频率是如何统计的，还有就是可以绘制神经元膜电位的图像吗？谢谢

**Comment by thiswinex** [comment]
关于firing rate和膜电位的统计你可以借助hooks机制实现，统计量得到之后就可以绘制对应的图像

**Comment by chenjiefighting** [comment]
非常感谢，我查了一下，可以使用hook机制获得某一层的feature map，对于firing rate可以讲得具体一点吗，或者有什么书籍或者资料推荐一下吗，拜谢大佬

**Comment by thiswinex** [comment]
拿到了每个timestamp下的脉冲特征图，就可以统计firing rate。bp-base的snn优化方法是统计ai兴起后才重新出现的，所以关于firing rate对优化的影响，可以搜索一下近年来相关的论文。
