### ISSUE TITLE
CifarNet 损失降不下来

### ISSUE THREAD

**Issue by wang1239435478** [thiswinex/STBP-simple#13]
你好，我用代码中提供的CifarNet对Cifar100数据集进行分类（将最后一层全连接的神经元个数改成100，其他参数没有改动），训练了400多个epoch发现损失始终降不下来，测试集准确率也一直保持在1%（随机水平），可能是什么原因导致的呢？

**Comment by thiswinex** [comment]
我推荐你监控训练时的梯度。stbp是梯度近似方法，由于经过梯度近似后的冲击函数仍只有一小段存在梯度（由超参a控制） 训练时很容易出现大量零梯度的激活。这需要仔细调整超参a以及vth、tau（控制发放）。

另外，你可以试试将spike函数稍作修改，将vth前后的梯度由0改成一个非常小的、会decay的值，相对应的在近似区外也能提供非常小的梯度（参考leaky relu）。我没有尝试过这一方法，也不清楚是否有论文尝试过这一方法，但也许会有用。
