### ISSUE TITLE
几个超参数设置的问题

### ISSUE THREAD

**Issue by CannonWWW** [thiswinex/STBP-simple#15]
请问有人跑过MNISTNet的实验吗，几个超参数是怎么设置的呢，我用论文里的数据跑了一下也出现了loss降不下去的问题

**Comment by thiswinex** [comment]
MNIST数据集是比较好收敛的，采用STBP原文的参数就可以（没记错的话Vth和衰减tau都是0.3）

**Comment by CannonWWW** [comment]
> MNIST数据集是比较好收敛的，采用STBP原文的参数就可以（没记错的话Vth和衰减tau都是0.3）

但是我看原文并不是这个，我还是用这个参数跑一下试试吧，alpha直接用0.5可以吗

**Comment by thiswinex** [comment]
> > MNIST数据集是比较好收敛的，采用STBP原文的参数就可以（没记错的话Vth和衰减tau都是0.3）
> 
> 但是我看原文并不是这个，我还是用这个参数跑一下试试吧，alpha直接用0.5可以吗

我确认了下原文，确实mnist不是这个设置，0.3应该是我跑nmnist和cifar的参数。我记得我测试过使用原文mnist的参数能够收敛，但是时间隔得太久了我也无法完全保证记忆准确。alpha和论文对齐即可。

**Comment by CannonWWW** [comment]
成功了，在MNIST上收敛的速度很快，感谢耐心解答

> > > MNIST数据集是比较好收敛的，采用STBP原文的参数就可以（没记错的话Vth和衰减tau都是0.3）
> > 
> > 
> > 但是我看原文并不是这个，我还是用这个参数跑一下试试吧，alpha直接用0.5可以吗
> 
> 我确认了下原文，确实mnist不是这个设置，0.3应该是我跑nmnist和cifar的参数。我记得我测试过使用原文mnist的参数能够收敛，但是时间隔得太久了我也无法完全保证记忆准确。alpha和论文对齐即可。
调了参数之后收敛的很快，感谢作者耐心的解答！

**Comment by CannonWWW** [comment]
> > > MNIST数据集是比较好收敛的，采用STBP原文的参数就可以（没记错的话Vth和衰减tau都是0.3）
> > 
> > 
> > 但是我看原文并不是这个，我还是用这个参数跑一下试试吧，alpha直接用0.5可以吗
> 
> 我确认了下原文，确实mnist不是这个设置，0.3应该是我跑nmnist和cifar的参数。我记得我测试过使用原文mnist的参数能够收敛，但是时间隔得太久了我也无法完全保证记忆准确。alpha和论文对齐即可。
成功了，在MNIST上收敛的速度很快，感谢耐心解答

**Comment by CannonWWW** [comment]
> 我确认了下原文，确实mnist不是这个设置，0.3应该是我跑nmnist和cifar的参数。我记得我测试过使用原文mnist的参数能够收敛，但是时间隔得太久了我也无法完全保证记忆准确。alpha和论文对齐即可。

成功了，在MNIST上收敛的速度很快，感谢耐心解答

**Comment by thiswinex** [comment]
有问题请随时重新打开issue
