### ISSUE TITLE
关于准确率

### ISSUE THREAD

**Issue by manwu1994** [thiswinex/STBP-simple#2]
hello, 请问您能复现 CIFAR10 92%  （time_steps=2）的结果吗？
谢谢~

**Comment by thiswinex** [comment]
我跑过类似的实验，具体的实验记录我没有存下来，但可以说明的是网络在cifar10上的收敛相比mnist特别慢，至少需要400epoch。继续跑到600-800epoch应该可以到85-90%的acc。

**Comment by manwu1994** [comment]
> 我跑过类似的实验，具体的实验记录我没有存下来，但可以说明的是网络在cifar10上的收敛相比mnist特别慢，至少需要400epoch。继续跑到600-800epoch应该可以到85-90%的acc。

深度太深，spike都消失了....我试着复现他们的文章就没有达到这个acc...

**Comment by manwu1994** [comment]
还有一个问题，如果用Average pooling的话，会不会就失去了event-driven的优势的，其实就是浮点计算了，只有在输入层是binary representation....如果利用stride来减少size，信息损失就非常大.....

**Comment by thiswinex** [comment]
> 还有一个问题，如果用Average pooling的话，会不会就失去了event-driven的优势的，其实就是浮点计算了，只有在输入层是binary representation....如果利用stride来减少size，信息损失就非常大.....

使用AvgPool更可能是出于硬件部署的目的，AvgPool可以更方便的转换成对应的卷积层。至于何种下采样方法更好的问题我没有仔细思考过，你可以尝试做做实验。

**Comment by thiswinex** [comment]
> > 我跑过类似的实验，具体的实验记录我没有存下来，但可以说明的是网络在cifar10上的收敛相比mnist特别慢，至少需要400epoch。继续跑到600-800epoch应该可以到85-90%的acc。
> 
> 深度太深，spike都消失了....我试着复现他们的文章就没有达到这个acc...

可以尝试邮件直接和原作者讨论。

**Comment by manwu1994** [comment]
嗯嗯，已发邮件，但是老师没回复我...谢谢！！
