### ISSUE TITLE
关于layers中的simwin

### ISSUE THREAD

**Issue by zjuls** [thiswinex/STBP-simple#4]
作者你好！非常感谢你的复现工作！我在阅读代码时，发现layers.py中的simwin并没有在下文中用到，而在forward过程中，用的是steps这一变量，是否steps是time window，还是笔误呢？感谢指导！

**Comment by thiswinex** [comment]
simwin是simulation_window的简写，和dt一样是dvs等视频类任务中的超参数。但由于simwin = dt * steps，所以实际上只要确认其二即可求余下那个。forward过程只需要用steps，所以simwin和dt是任务相关的超参，我后续更新的时候会去掉。
