### ISSUE TITLE
为啥我把脉冲序列的模拟时长调大了，反而训练效果不好呢？

### ISSUE THREAD

**Issue by Precola** [thiswinex/STBP-simple#7]
我把steps由2改成10了，200多个回合了，准确率一直是10%欸

**Comment by thiswinex** [comment]
stbp方法受超参影响较大（主要是steps，vth，tau）。建议通过观察各层firing rate来仔细调整超参。

在 2021年7月16日星期五，Cola ***@***.***> 写道：
