### ISSUE TITLE
On coding error in LIF model

### ISSUE THREAD

**Issue by kamata1729** [thiswinex/STBP-simple#8]
https://github.com/thiswinex/STBP-simple/blob/dca9590b465c5cb37b3828bf6888c6857ad4238b/layers.py#L40

I think this line should be `spikeAct(u_t1_n1)`, because LIF model is implemented in this way
https://github.com/thiswinex/STBP-simple/blob/dca9590b465c5cb37b3828bf6888c6857ad4238b/layers.py#L23

**Comment by thiswinex** [comment]
That's actually a bug and thanks a lot. I have fixed it in dev branch:
https://github.com/thiswinex/STBP-simple/blob/3284f342b1e88c1cb0ce9669d8040ca990af713a/example/stbp/layers.py#L30
Sorry I'm too busy to finish develop new features so I haven't merged this branch yet. I'll update it asap.
