### ISSUE TITLE
加入tdBatchNorm后，训练过程没问题，但测试过程准确度始终为10%左右

### ISSUE THREAD

**Issue by zjuls** [thiswinex/STBP-simple#9]
感谢对tdNorm的复现！但在使用过程中发现，加入tdBatchNorm后，训练过程没问题，但测试过程准确度始终为10%左右，如下所示？模型为Resnet-34，数据集为CIFAR-10。想请教一下这是什么原因？感谢！
训练阶段：
![图片](https://user-images.githubusercontent.com/52598916/132937446-cca05972-27dc-4871-95f5-453145593859.png)
测试阶段：
![图片](https://user-images.githubusercontent.com/52598916/132937461-ac6efca9-f221-4193-9ca9-72e0fb751ab5.png)

**Comment by thiswinex** [comment]
感谢关注。从图中我并不好判断是什么原因所致，也可能是单纯的收敛过慢。我建议可以先做一下对比实验，比如观察去掉tdBN的收敛情况，或是观察在MNIST/NMNIST上的收敛情况，来确定是否是tdBN的问题。或是检查一下在shortcut部分alpha是否设置正确，这个参数对firing rate影响较大。

之前我的实验显示模型在CIFAR10的收敛速度远慢于MNIST，stbp虽然能提供直接优化的方法，但这个优化问题还是太过复杂（耦合了recurrent和ste量化），我没有继续研究。

**Comment by JiaqingFu** [comment]
@thiswinex 我看了下tdbn的实现，是不是少了论文反归一化的实现。如图红框公式未实现
![image](https://user-images.githubusercontent.com/12004134/158298015-a0d85e7b-caab-4bda-9b9f-66433e4c68e3.png)

**Comment by zjuls** [comment]
我发现这个问题是因为多卡并行而出现的，单卡+小batch没有问题，但是多卡并行会出现上述的问题，请问是为什么呢？

**Comment by thiswinex** [comment]
非常抱歉没有在多卡上测试过这个模型。个人猜测如果是多卡+tdBN才会出现的话，可能是syncBN的问题，但我觉得不应该影响这么严重。

**Comment by zjuls** [comment]
我也是这么想的，现在考虑简单粗暴的reshape，将事件维度reshape到channel上试一下，十分感谢！
